# Generated by Django 4.1.4 on 2023-11-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='default+product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_about',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=12),
        ),
    ]
